version: 0.2
env:
  variables:
    ECR_BASE: 241078504042.dkr.ecr.us-east-1.amazonaws.com
    PROJECT_NAME: ds4a-dash-app
    PROJECT_REPO: /ds4a-run-dash
    VERSION: 0.0.2
    ENV_CONTAINER: 241078504042.dkr.ecr.us-east-1.amazonaws.com/base-images:latest
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo starting build prod branch
      - export STARTINGPOINT=$(pwd)
      - echo $STARTINGPOINT
      - pip install awscli pyyaml
  pre_build:
    commands:
      - echo starting process
      - export ECR_REPO=${ECR_BASE}${PROJECT_REPO}
      - echo $ECR_REPO
      - echo starting copy folders
      - cd aws_env
      - cp -R ../assets assets
      - cp -R ../components components
      - cp -R ../environment environment
      - cp -R ../layout layout
      - cp -R ../pages pages
      - cp -R ../utils utils
      - cp ../app.py app.py
      - cp ../gunicorn_config.py gunicorn_config.py
      - cp ../index.py index.py
      - cp ../requirements.txt requirements.txt 
      - cp ../routes.py routes.py     
      - echo logging in to Project AWS ECR...
      - ls
      - aws --region ${AWS_DEFAULT_REGION} ecr get-login-password | docker login --password-stdin --username AWS "${ECR_BASE}"
      - echo logging into ${ECR_REPO}
  build:
    commands:
      - echo ------------CREATING IMAGE---------------------
      - echo swapping current image from release to rollback
      - docker pull ${ECR_REPO}:${PROJECT_NAME}_release || true 
      - docker tag ${ECR_REPO}:${PROJECT_NAME}_release ${ECR_REPO}:${PROJECT_NAME}_rollback || true
      - echo this is an image creation
      - docker build -t ${ECR_REPO}:${PROJECT_NAME}-${VERSION} -t ${ECR_REPO}:${PROJECT_NAME}_release --build-arg ENV_CONTAINER=$ENV_CONTAINER .
      - docker push ${ECR_REPO}:${PROJECT_NAME}-${VERSION}
      - docker push ${ECR_REPO}:${PROJECT_NAME}_release
      - docker push ${ECR_REPO}:${PROJECT_NAME}_rollback || true
      - echo created image

