version: "3.7"

services:
  clean-dash:
    build:
      context: .
    image: clean-dash:latest
    container_name: clean-dash
    ports:
      - "8085"
    environment:
      - TARGET=latest
    restart: unless-stopped